### ISSUE TITLE
Capture JS and save in DB

### ISSUE THREAD

**Issue by rafibarash** [csci4950tgt/honeyclient#15]

**Comment by tantric-slug** [comment]
I believe this is finished with the most recent PR right?

**Comment by tantric-slug** [comment]
ahh, after running I see, we are capturing the js but it is seemingly not stored in the database as of now?

**Comment by alejx** [comment]
@tantric-slug I can see beautified js files in DB as of now. Try some website other than google.com you will see those js files, hopefully.

**Comment by tantric-slug** [comment]
Working for me now, it may have been due to using google.com
