### ISSUE TITLE
RFC: Do not use filename when requesting JavaScript files

### ISSUE THREAD

**Issue by alejx** [csci4950tgt/honeyclient#20]
When I was implementing https://github.com/csci4950tgt/frontend/issues/36, I found that we cannot use filename when requesting artifacts via API. Some of the JavaScript files (possibly related to tracking or ads) are blocked by ad blockers. I suggest that we can store a unique ID for each artifact in the database and use that unique ID to request instead of the filename. Any thoughts? @williamtdr @rafibarash

**Comment by williamtdr** [comment]
@alejx Could you explain this a bit more? If files are erring out because of client-side ad-blocking, we should surface that - and ask the user to disable their ad-blocking software on this site.

**Comment by alejx** [comment]
@williamtdr When fetching the JavaScript files from the API, the GET request is blocked due to `ERR_BLOCKED_BY_CLIENT` because the filename of the JavaScript file triggered the ad blocker. (e.g. `GET http://localhost:8080/api/tickets/18/artifacts/static.doubleclick.net/ad_status.js `, here `ad_status.js` might be a keyword of the ad blocker.) So I believe that if we use something other than the filename of the artifacts, the request will not trigger the ad blocker.

**Comment by williamtdr** [comment]
Sure, that makes sense. In that case, we should catch the error and throw up an `alert()` or something similar. Smarter ad blockers will use fingerprinting on the result that's being returned anyway, and block or change it - it makes more sense to ask the user to turn off their ad blocker for this site.
