### ISSUE TITLE
Integrate Honeyclient with Express.js to optimize data communication between App containers.

### ISSUE THREAD

**Issue by tantric-slug** [csci4950tgt/honeyclient#7]
It would be beneficial to create an express server that works with our honeyclient utilities so that our React frontend can efficiently communicate with the honeyclient via a proxy.

This would remove the need for some unnecessary temporary and persistent data storage (i.e. input .json files) and allow for direct, simple, and efficient transfer and requests of information.

**Comment by rafibarash** [comment]
seems like we will be checking in with the database for new issues to be processed instead
